version: "3"

services:
  db:
    image: mariadb:10.11
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql:Z
    env_file:
      - ./db.env
    networks:
      - matomo_network

  app:
    image: matomo:fpm-alpine
    restart: always
    volumes:
      - ./config:/var/www/html/config:z
      - ./logs:/var/www/html/logs:z
      - matomo:/var/www/html:z
    environment:
      - MATOMO_DATABASE_HOST=db
      - PHP_MEMORY_LIMIT=2048M
    env_file:
      - ./db.env
    networks:
      - matomo_network

  web:
    image: nginx:alpine
    restart: always
    volumes:
      - matomo:/var/www/html:z
      # see https://github.com/matomo-org/matomo-nginx
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:z
      - /opt/certs:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    networks:
      - matomo_network

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - /opt/certs:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/www/certbot:/var/www/certbot
    command: renew
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done"
    networks:
      - matomo_network

networks:
  matomo_network:
    driver: bridge

volumes:
  db:
  matomo: